package alerts

import (
	"fmt"
	"strings"
	"time"
)

// GenerateReport produces a simple HTML email body for the triggered alerts.
func GenerateReport(alerts []Alert) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #f5f5f5; }
  h2 { color: #333; border-bottom: 2px solid #e74c3c; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  th { background: #2c3e50; color: white; padding: 10px 14px; text-align: left; font-size: 13px; }
  td { padding: 10px 14px; border-bottom: 1px solid #eee; font-size: 14px; }
  tr:last-child td { border-bottom: none; }
  .up   { color: #27ae60; font-weight: bold; }
  .down { color: #e74c3c; font-weight: bold; }
  .footer { margin-top: 16px; font-size: 12px; color: #999; }
</style>
</head>
<body>
`)

	sb.WriteString(fmt.Sprintf("<h2>🚨 Price Alerts — %s</h2>\n", time.Now().Format("02 Jan 2006 15:04")))
	sb.WriteString("<table>\n")
	sb.WriteString("  <tr><th>Stock</th><th>Ticker</th><th>Open</th><th>Current</th><th>Change</th><th>Threshold</th></tr>\n")

	for _, a := range alerts {
		changeClass := "up"
		changeSign := "+"
		if a.ChangePercent < 0 {
			changeClass = "down"
			changeSign = ""
		}
		thresholdSign := "+"
		if a.Threshold < 0 {
			thresholdSign = ""
		}
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td>%s</td>
    <td><strong>%s</strong></td>
    <td>%.2f</td>
    <td>%.2f</td>
    <td class="%s">%s%.2f%%</td>
    <td>%s%.1f%%</td>
  </tr>
`,
			a.Stock.Name, a.Stock.Ticker,
			a.OpenPrice, a.CurrentPrice,
			changeClass, changeSign, a.ChangePercent,
			thresholdSign, a.Threshold,
		))
	}

	sb.WriteString("</table>\n")
	sb.WriteString(`<p class="footer">Generated by stock-checker</p>`)
	sb.WriteString("</body>\n</html>")

	return sb.String()
}

// EmailSubject builds a concise subject line summarising the alerts.
func EmailSubject(alerts []Alert) string {
	if len(alerts) == 0 {
		return ""
	}
	parts := make([]string, 0, len(alerts))
	for _, a := range alerts {
		sign := "+"
		if a.ChangePercent < 0 {
			sign = ""
		}
		parts = append(parts, fmt.Sprintf("%s %s%.1f%%", a.Stock.Ticker, sign, a.ChangePercent))
	}
	return fmt.Sprintf("🚨 Price Alert: %s", strings.Join(parts, ", "))
}
